language: php

php:
  - 5.5
  - 5.6
  - 7
  - 7.1

services:
  - docker

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - ./tests/prep.sh
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v