language: php

php:
  - 5.3
  - 5.4
  - 5.5

node_js:
  - "0.11"
  - "0.10"

services:
  - redis-server

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - cd tests && npm install && cd ..
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v